version: '3.8'

services:
  whitewhale-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whitewhale-portfolio
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
